#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const path          = require('path'),
      gen_license   = require('../lib/generate_license'),
      licenses      = require('../lib/licenses').licenses,
      optimist      = require('optimist')
                          .describe('l', 'Font License: ' + Object.keys(licenses).join(', '))
                          .alias('l', 'license')
                          .demand('l')
                          .usage('usage: ' + path.basename(__filename) +
                                ' <target_dir> [options]'),
      argv          = optimist.argv;

var targetName = argv._[0];
if (!targetName) {
  optimist.showHelp();
  process.exit(1);
}

if (!licenses[argv.l]) {
  optimist.showHelp();
  process.exit(1);
}

gen_license.write({
  target_dir: targetName,
  license: licenses[argv.l]
});
