#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const path          = require('path'),
      directory     = require('../lib/directory'),
      generic_config        
                    = require('../lib/generic_config')
      program       = require('commodore')
                          .description('create a connect-fonts font pack from the .ttf fonts located in a directory')
                          .version('0.0.1')
                          .option('--an <author_name>', 'Author name')
                          .loadable('an')
                          .demand('an')
                          .option('--ae <author_email>', 
                              'Author email(s) - comma separated list if more than one')
                          .loadable('ae')
                          .demand('ae')
                          .option('--au <author_urls>', 
                              'Author url(s) - comma separated list if more than one')
                          .loadable('au')
                          .option('--at <author_twitter>', 'Author twitter')
                          .loadable('at')
                          .option('--ag <author_github>', 'Author github')
                          .loadable('ag')
                          .option('--pn <package_name>', 'Package name')
                          .demand('pn')
                          .option('--ph <project_homepage_url>', 'Project homepage URL')
                          .option('--pr <project_repo_url>', 'Project repo URL')
                          .option('--pb <project_bugtracker_url>', 'Project bug tracker URL')
                          .option('-c <credits>', 'Credits')
                          .option('--sp <source_path>', 'Source Path')
                          .demand('sp')
                          .option('--tp <target_path>', 'Target Path')
                          .demand('tp')
                          .load(generic_config.config_path)
                          .parse(process.argv);


var sourcePath = generic_config.resolve(process.cwd(), program.sp);
var targetPath = generic_config.resolve(process.cwd(), program.tp);

directory.process(sourcePath, targetPath, program, function(err) {
  if (err) {
    console.error(String(err));
    process.exit(1);
  }
});


