#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const path          = require('path'),
      generate_fonts_from_ttf
                    = require('../lib/generate_fonts_from_ttf')
      optimist      = require('optimist')
                          .usage('usage: ' + path.basename(__filename) +
                                ' <filename> <target_dir>')
      argv          = optimist.argv;

var fileName = argv._[0];
var targetName = argv._[1];

if (!(fileName && targetName)) {
  optimist.showHelp();
  process.exit(1);
}

generate_fonts_from_ttf.write(fileName, targetName, function(err) {
  if (err) {
    var msg = String(err);
    if (msg === "not a ttf") {
      console.error(path.basename(__filename) + " only works with ttf files");
    }
    else {
      console.error(msg);
    }
    process.exit(1);
  }
});


