#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


const path          = require('path'),
      gen_readme    = require('../lib/generate_readme'),
      licenses      = require('../lib/licenses').licenses,
      optimist      = require('optimist')
                          .describe('l', 'Font License: ' + Object.keys(licenses).join(', '))
                          .alias('l', 'license')
                          .demand('l')
                          .describe('fn', 'font name(s) - comma separated list if more than one')
                          .demand('fn')
                          .describe('ff', 'font family')
                          .demand('ff')
                          .describe('an', 'Author name')
                          .demand('an')
                          .describe('ae', 'Author email(s) - comma separated list if more than one')
                          .demand('ae')
                          .describe('au', 'Author url(s) - comma separated list if more than one')
                          .demand('au')
                          .describe('at', 'Author twitter')
                          .describe('ag', 'Author github')
                          .describe('pn', 'Package name')
                          .demand('pn')
                          .describe('ph', 'Project homepage URL')
                          .describe('pr', 'Project repo URL')
                          .describe('pb', 'Project bug tracker URL')
                          .describe('c', 'Credits')
                          .usage('usage: ' + path.basename(__filename) +
                                ' <target_dir> [options]'),
      argv          = optimist.argv;

var targetName = argv._[0];
if (!targetName) {
  optimist.showHelp();
  process.exit(1);
}

if (!licenses[argv.l]) {
  optimist.showHelp();
  process.exit(1);
}

gen_readme.write({
  target_dir: targetName,
  author: {
    name: argv.an,
    emails: argv.ae,
    urls: argv.au,
    githubs: argv.ag,
    twitter: argv.at
  },
  package: {
    name: argv.pn,
    homepage: argv.ph || false,
    repourl: argv.pr || false,
    bugsurl: argv.pb || false
  },
  font: {
    names: argv.fn,
    family: argv.ff
  },
  credits: argv.c,
  license: licenses[argv.l]
});


