#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const path          = require('path'),
      generic_config        
                    = require('../lib/generic_config')
      gen_license   = require('../lib/generate_license'),
      licenses      = require('../lib/licenses').licenses,
      program       = require('commodore')
                          .option('-l, --license <license>', 'Font License: ' + Object.keys(licenses).join(', '))
                          .demand('l')
                          .option('--tp <target_path>', 'Target Path')
                          .demand('tp')
                          .parse(process.argv);

if (!licenses[program.license]) {
  program.showHelp();
  process.exit(1);
}

gen_license.write({
  target_dir: generic_config.resolve(process.cwd(), program.tp),
  license: licenses[program.license]
}, function(err) {
  if (err) {
    console.error(String(err));
    process.exit(1);
  }
});
