#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const path          = require('path'),
      fs            = require('fs')
      directory_metadata = require('../lib/directory_metadata'),
      optimist      = require('optimist')
                          .usage('usage: ' + path.basename(__filename) +
                                ' <directory> <target_dir>'),
      argv          = optimist.argv;

var directoryName = path.resolve(process.cwd(), argv._[0]);
var targetName = argv._[1];

if (!(directoryName && targetName)) {
  optimist.showHelp();
  process.exit(1);
}

directory_metadata(directoryName, function(err, metaInfo) {
  if (err) {
    console.error(String(err));
    process.exit(1);
  }

  console.log(metaInfo);
});
