#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const program     = require('commodore')
                        .version('0.0.1')
                        .parse(process.argv),
      config_json = require('../lib/config_connect_fonts');

config_json.ask(function(err, config) {
  if (err) return process.exit(1);
  process.exit(0);
});

